import assert from "node:assert/strict";
import test from "node:test";
import { hash, Algorithm } from "@node-rs/argon2";
import { createApp } from "../server.mjs";
import { newId, timestamp } from "../db.mjs";

const env = { AUTH_ENABLED: "true", SESSION_SECRET: "a".repeat(48), INTERNAL_AGENT_SECRET: "b".repeat(48), LIVEKIT_API_KEY: "test", LIVEKIT_API_SECRET: "test-secret", PUBLIC_RTC_HOST: "rtc.example.test", DATABASE_PATH: ":memory:", SESSION_TTL_HOURS: "1", LOGIN_RATE_LIMIT_ATTEMPTS: "2", LOGIN_RATE_LIMIT_WINDOW_MINUTES: "15", MAX_ACTIVE_VOICE_SESSIONS_PER_USER: "1", VOICE_SESSION_RATE_LIMIT_PER_MINUTE: "1" };
async function fixture() {
  const { app, db } = createApp({ env });
  const server = await new Promise((resolve) => { const instance = app.listen(0, "127.0.0.1", () => resolve(instance)); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const addUser = async (username) => { const time = timestamp(); db.prepare("INSERT INTO users (id, username, password_hash, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").run(newId(), username, await hash("correct horse battery staple", { algorithm: Algorithm.Argon2id }), time, time); };
  const request = (url, options = {}) => fetch(`${base}${url}`, options);
  return { base, db, request, addUser, close: () => new Promise((resolve) => server.close(resolve)) };
}
function cookie(response, name) { const match = response.headers.get("set-cookie").match(new RegExp(`(?:^|,\\s*)${name}=([^;]*)`)); return match ? `${name}=${match[1]}` : null; }
async function login(app, username, password = "correct horse battery staple") {
  const csrfResponse = await app.request("/api/auth/csrf"); const loginCookie = cookie(csrfResponse, "vbb_login_csrf"); const { csrfToken } = await csrfResponse.json();
  const response = await app.request("/api/login", { method: "POST", headers: { cookie: loginCookie, origin: app.base, "content-type": "application/json", "x-csrf-token": csrfToken }, body: JSON.stringify({ username, password }) });
  return { response, cookie: response.ok ? cookie(response, "vbb_session") : null };
}
async function session(app, sessionCookie) { const response = await app.request("/api/session", { headers: { cookie: sessionCookie } }); return { response, data: response.ok ? await response.json() : null }; }
async function voiceSession(app, sessionCookie) { const active = await session(app, sessionCookie); return app.request("/api/voice/session", { method: "POST", headers: { cookie: sessionCookie, origin: app.base, "x-csrf-token": active.data.csrfToken, "content-type": "application/json" }, body: "{}" }); }

test("authentication gates voice and conversation APIs", async () => { const app = await fixture(); try { assert.equal((await app.request("/api/voice/session", { method: "POST" })).status, 401); assert.equal((await app.request("/api/conversations")).status, 401); await app.addUser("alice"); const invalid = await login(app, "alice", "wrong password"); assert.equal(invalid.response.status, 401); const signedIn = await login(app, "alice"); assert.equal(signedIn.response.status, 200); const active = await session(app, signedIn.cookie); assert.equal(active.data.username, "alice"); } finally { await app.close(); } });
test("logout and expiration revoke access", async () => { const app = await fixture(); try { await app.addUser("alice"); const signedIn = await login(app, "alice"); const active = await session(app, signedIn.cookie); const logout = await app.request("/api/logout", { method: "POST", headers: { cookie: signedIn.cookie, origin: app.base, "x-csrf-token": active.data.csrfToken, "content-type": "application/json" }, body: "{}" }); assert.equal(logout.status, 204); assert.equal((await app.request("/api/conversations", { headers: { cookie: signedIn.cookie } })).status, 401); const second = await login(app, "alice"); app.db.prepare("UPDATE sessions SET expires_at = 0 WHERE token_hash IS NOT NULL").run(); assert.equal((await app.request("/api/conversations", { headers: { cookie: second.cookie } })).status, 401); } finally { await app.close(); } });
test("saved chats are isolated by user", async () => { const app = await fixture(); try { await app.addUser("alice"); await app.addUser("bob"); const alice = await login(app, "alice"); const bob = await login(app, "bob"); const aliceId = app.db.prepare("SELECT id FROM users WHERE username = 'alice'").get().id; const conversationId = newId(); const time = timestamp(); app.db.prepare("INSERT INTO conversations (id, user_id, title, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").run(conversationId, aliceId, "Private", time, time); assert.equal((await app.request(`/api/conversations/${conversationId}`, { headers: { cookie: bob.cookie } })).status, 404); assert.deepEqual((await (await app.request("/api/conversations", { headers: { cookie: bob.cookie } })).json()).conversations, []); } finally { await app.close(); } });
test("login rate limit applies", async () => { const app = await fixture(); try { await app.addUser("alice"); await login(app, "alice", "wrong"); await login(app, "alice", "wrong"); assert.equal((await login(app, "alice", "wrong")).response.status, 429); } finally { await app.close(); } });
test("voice rate limit and explicit save preserve only finalized messages", async () => { const app = await fixture(); try { await app.addUser("alice"); const signedIn = await login(app, "alice"); const voiceResponse = await voiceSession(app, signedIn.cookie); assert.equal(voiceResponse.status, 200); const voice = await voiceResponse.json(); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM messages").get().count, 0); const internal = await app.request(`/internal/voice-sessions/${voice.identity}/messages`, { method: "POST", headers: { authorization: `Bearer ${env.INTERNAL_AGENT_SECRET}`, "content-type": "application/json" }, body: JSON.stringify({ sourceId: "final-user-1", role: "user", content: "A finalized turn" }) }); assert.equal(internal.status, 204); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM messages").get().count, 0); const active = await session(app, signedIn.cookie); const saved = await app.request("/api/conversations/save", { method: "POST", headers: { cookie: signedIn.cookie, origin: app.base, "x-csrf-token": active.data.csrfToken, "content-type": "application/json" }, body: JSON.stringify({ voiceSessionId: voice.voiceSessionId }) }); const { conversationId } = await saved.json(); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM messages WHERE conversation_id = ?").get(conversationId).count, 1); const duplicate = await app.request(`/internal/voice-sessions/${voice.identity}/messages`, { method: "POST", headers: { authorization: `Bearer ${env.INTERNAL_AGENT_SECRET}`, "content-type": "application/json" }, body: JSON.stringify({ sourceId: "final-user-1", role: "user", content: "A finalized turn" }) }); assert.equal(duplicate.status, 204); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM messages WHERE conversation_id = ?").get(conversationId).count, 1); assert.equal((await voiceSession(app, signedIn.cookie)).status, 429); } finally { await app.close(); } });
