import assert from "node:assert/strict";
import test from "node:test";
import { hash, Algorithm } from "@node-rs/argon2";
import { createApp } from "../server.mjs";
import { newId, timestamp } from "../db.mjs";

const env = { AUTH_ENABLED: "true", SESSION_SECRET: "a".repeat(48), INTERNAL_AGENT_SECRET: "b".repeat(48), LIVEKIT_API_KEY: "test", LIVEKIT_API_SECRET: "test-secret", PUBLIC_RTC_HOST: "rtc.example.test", DATABASE_PATH: ":memory:", SESSION_TTL_HOURS: "1", LOGIN_RATE_LIMIT_ATTEMPTS: "2", LOGIN_RATE_LIMIT_WINDOW_MINUTES: "15", MAX_ACTIVE_VOICE_SESSIONS_PER_USER: "1", VOICE_SESSION_RATE_LIMIT_PER_MINUTE: "1" };
async function fixture() {
  const { app, db } = createApp({ env });
  const server = await new Promise((resolve) => { const instance = app.listen(0, "127.0.0.1", () => resolve(instance)); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const addUser = async (username) => { const time = timestamp(); db.prepare("INSERT INTO users (id, username, password_hash, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").run(newId(), username, await hash("correct horse battery staple", { algorithm: Algorithm.Argon2id }), time, time); };
  const request = (url, options = {}) => fetch(`${base}${url}`, options);
  return { base, db, request, addUser, close: () => new Promise((resolve) => server.close(resolve)) };
}
function cookie(response, name) { const match = response.headers.get("set-cookie").match(new RegExp(`(?:^|,\\s*)${name}=([^;]*)`)); return match ? `${name}=${match[1]}` : null; }
async function login(app, username, password = "correct horse battery staple") {
  const csrfResponse = await app.request("/api/auth/csrf"); const loginCookie = cookie(csrfResponse, "vbb_login_csrf"); const { csrfToken } = await csrfResponse.json();
  const response = await app.request("/api/login", { method: "POST", headers: { cookie: loginCookie, origin: app.base, "content-type": "application/json", "x-csrf-token": csrfToken }, body: JSON.stringify({ username, password }) });
  return { response, cookie: response.ok ? cookie(response, "vbb_session") : null };
}
async function session(app, sessionCookie) { const response = await app.request("/api/session", { headers: { cookie: sessionCookie } }); return { response, data: response.ok ? await response.json() : null }; }
async function voiceSession(app, sessionCookie) { const active = await session(app, sessionCookie); return app.request("/api/voice/session", { method: "POST", headers: { cookie: sessionCookie, origin: app.base, "x-csrf-token": active.data.csrfToken, "content-type": "application/json" }, body: "{}" }); }
async function mutation(app, sessionCookie, url, method, body = "{}") { const active = await session(app, sessionCookie); return app.request(url, { method, headers: { cookie: sessionCookie, origin: app.base, "x-csrf-token": active.data.csrfToken, "content-type": "application/json" }, body }); }
function finalized(app, identity, sourceId, role, content) { return app.request(`/internal/voice-sessions/${identity}/messages`, { method:"POST", headers:{ authorization:`Bearer ${env.INTERNAL_AGENT_SECRET}`, "content-type":"application/json" }, body:JSON.stringify({ sourceId, role, content }) }); }

test("authentication gates voice and conversation APIs", async () => { const app = await fixture(); try { assert.equal((await app.request("/api/voice/session", { method: "POST" })).status, 401); assert.equal((await app.request("/api/conversations")).status, 401); await app.addUser("alice"); const invalid = await login(app, "alice", "wrong password"); assert.equal(invalid.response.status, 401); const signedIn = await login(app, "alice"); assert.equal(signedIn.response.status, 200); const active = await session(app, signedIn.cookie); assert.equal(active.data.username, "alice"); } finally { await app.close(); } });
test("logout and expiration revoke access", async () => { const app = await fixture(); try { await app.addUser("alice"); const signedIn = await login(app, "alice"); const active = await session(app, signedIn.cookie); const logout = await app.request("/api/logout", { method: "POST", headers: { cookie: signedIn.cookie, origin: app.base, "x-csrf-token": active.data.csrfToken, "content-type": "application/json" }, body: "{}" }); assert.equal(logout.status, 204); assert.equal((await app.request("/api/conversations", { headers: { cookie: signedIn.cookie } })).status, 401); const second = await login(app, "alice"); app.db.prepare("UPDATE sessions SET expires_at = 0 WHERE token_hash IS NOT NULL").run(); assert.equal((await app.request("/api/conversations", { headers: { cookie: second.cookie } })).status, 401); } finally { await app.close(); } });
test("saved chats are isolated by user", async () => { const app = await fixture(); try { await app.addUser("alice"); await app.addUser("bob"); const alice = await login(app, "alice"); const bob = await login(app, "bob"); const aliceId = app.db.prepare("SELECT id FROM users WHERE username = 'alice'").get().id; const conversationId = newId(); const time = timestamp(); app.db.prepare("INSERT INTO conversations (id, user_id, title, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").run(conversationId, aliceId, "Private", time, time); assert.equal((await app.request(`/api/conversations/${conversationId}`, { headers: { cookie: bob.cookie } })).status, 404); assert.deepEqual((await (await app.request("/api/conversations", { headers: { cookie: bob.cookie } })).json()).conversations, []); } finally { await app.close(); } });
test("login rate limit applies", async () => { const app = await fixture(); try { await app.addUser("alice"); await login(app, "alice", "wrong"); await login(app, "alice", "wrong"); assert.equal((await login(app, "alice", "wrong")).response.status, 429); } finally { await app.close(); } });
test("voice rate limit and automatic persistence keep only finalized messages", async () => { const app = await fixture(); try { await app.addUser("alice"); const signedIn = await login(app, "alice"); const voice = await (await voiceSession(app, signedIn.cookie)).json(); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM conversations").get().count, 0); assert.equal((await finalized(app, voice.identity, "interim", "user", "   ")).status, 204); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM conversations").get().count, 0); assert.equal((await finalized(app, voice.identity, "final-user-1", "user", "A finalized turn")).status, 204); const conversationId = app.db.prepare("SELECT conversation_id FROM voice_sessions WHERE id = ?").get(voice.voiceSessionId).conversation_id; assert.ok(conversationId); assert.equal(app.db.prepare("SELECT title FROM conversations WHERE id = ?").get(conversationId).title, "A finalized turn"); assert.equal((await finalized(app, voice.identity, "final-assistant-1", "assistant", "A finalized reply")).status, 204); assert.equal((await finalized(app, voice.identity, "final-user-1", "user", "A finalized turn")).status, 204); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM messages WHERE conversation_id = ?").get(conversationId).count, 2); assert.equal((await voiceSession(app, signedIn.cookie)).status, 429); } finally { await app.close(); } });
test("rename validates titles and isolates saved chats", async () => { const app = await fixture(); try { await app.addUser("alice"); await app.addUser("bob"); const alice = await login(app, "alice"), bob = await login(app, "bob"); const aliceId = app.db.prepare("SELECT id FROM users WHERE username = 'alice'").get().id, bobId = app.db.prepare("SELECT id FROM users WHERE username = 'bob'").get().id, ownId = newId(), otherId = newId(), time = timestamp(); app.db.prepare("INSERT INTO conversations (id, user_id, title, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").run(ownId, aliceId, "Original", time, time); app.db.prepare("INSERT INTO conversations (id, user_id, title, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").run(otherId, bobId, "Private", time, time); assert.equal((await app.request(`/api/conversations/${ownId}`, { method: "PATCH" })).status, 401); assert.equal((await mutation(app, alice.cookie, `/api/conversations/${ownId}`, "PATCH", JSON.stringify({ title: "  Renamed chat  " }))).status, 200); assert.equal(app.db.prepare("SELECT title FROM conversations WHERE id = ?").get(ownId).title, "Renamed chat"); assert.equal((await mutation(app, alice.cookie, `/api/conversations/${otherId}`, "PATCH", JSON.stringify({ title: "Nope" }))).status, 404); assert.equal((await mutation(app, alice.cookie, `/api/conversations/${ownId}`, "PATCH", JSON.stringify({ title: "   " }))).status, 400); assert.equal((await mutation(app, alice.cookie, `/api/conversations/${ownId}`, "PATCH", JSON.stringify({ title: "x".repeat(121) }))).status, 400); } finally { await app.close(); } });
test("delete cascades messages and detaches active saved chats", async () => { const app = await fixture(); try { await app.addUser("alice"); await app.addUser("bob"); const alice = await login(app, "alice"), bob = await login(app, "bob"); const aliceId = app.db.prepare("SELECT id FROM users WHERE username = 'alice'").get().id, bobId = app.db.prepare("SELECT id FROM users WHERE username = 'bob'").get().id, conversationId = newId(), otherId = newId(), voiceId = newId(), time = timestamp(); app.db.prepare("INSERT INTO conversations (id, user_id, title, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").run(conversationId, aliceId, "Delete me", time, time); app.db.prepare("INSERT INTO conversations (id, user_id, title, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").run(otherId, bobId, "Private", time, time); app.db.prepare("INSERT INTO messages (id, conversation_id, source_id, role, content, sequence, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)").run(newId(), conversationId, "message-1", "user", "Saved message", 1, time); app.db.prepare("INSERT INTO voice_sessions (id, user_id, conversation_id, room, runtime_identity, created_at, expires_at) VALUES (?, ?, ?, ?, ?, ?, ?)").run(voiceId, aliceId, conversationId, `room-${voiceId}`, `voice-${voiceId}`, time, time + 60000); assert.equal((await app.request(`/api/conversations/${conversationId}`, { method: "DELETE" })).status, 401); assert.equal((await mutation(app, alice.cookie, `/api/conversations/${otherId}`, "DELETE")).status, 404); assert.equal((await mutation(app, alice.cookie, `/api/conversations/${conversationId}`, "DELETE")).status, 204); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM conversations WHERE id = ?").get(conversationId).count, 0); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM messages WHERE conversation_id = ?").get(conversationId).count, 0); assert.equal(app.db.prepare("SELECT conversation_id FROM voice_sessions WHERE id = ?").get(voiceId).conversation_id, null); assert.equal((await app.request(`/api/conversations/${conversationId}`, { headers: { cookie: alice.cookie } })).status, 404); } finally { await app.close(); } });

test("deleting an active autosaved chat creates a new conversation on the next turn", async () => { const app = await fixture(); try { await app.addUser("alice"); const signedIn = await login(app, "alice"), voice = await (await voiceSession(app, signedIn.cookie)).json(); await finalized(app, voice.identity, "first", "user", "First chat"); const firstId = app.db.prepare("SELECT conversation_id FROM voice_sessions WHERE id = ?").get(voice.voiceSessionId).conversation_id; assert.equal((await mutation(app, signedIn.cookie, `/api/conversations/${firstId}`, "DELETE")).status, 204); await finalized(app, voice.identity, "second", "user", "Second chat"); const secondId = app.db.prepare("SELECT conversation_id FROM voice_sessions WHERE id = ?").get(voice.voiceSessionId).conversation_id; assert.notEqual(secondId, firstId); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM conversations WHERE id = ?").get(firstId).count, 0); assert.equal(app.db.prepare("SELECT COUNT(*) AS count FROM messages WHERE conversation_id = ?").get(secondId).count, 1); } finally { await app.close(); } });
